language: go

go:
- 1.14.x

env:
  global:
  - GO111MODULE=on

before_install:
- go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
- go get github.com/securego/gosec/cmd/gosec

script:
- make

after_success:
- env | awk -F= '{print $1}'
- bash <(curl -s https://codecov.io/bash)
